### ISSUE TITLE
Question: How to create certain sensors?

### ISSUE THREAD

**Issue by mikesalz** [uvjustin/alarmdotcomajax#11]
FIrst, the integration is fantastic!  Thank you for the amazing work!  I saw the examples for creating sensors for doors and motion, and from the examples I figured out how to create sensors for windows and glass break, smoke, etc..  But I'm not sure how to create sensors for the following when the alarm is actually triggered.  Meaning, if someone breaks in and the alarm sounds, how do I detect that?

Below is my status.  Would you mind helping me out?  And perhaps adding these examples to the readme might be helpful to others.  Thank you so much!

> sensor_status: System OK, 126D57 - 1 is Closed, 126D57 - 2 is Closed, 126D57 - 3 is Closed, 126D57 - 4 is Closed, 126D57 - 5 is Closed, 126D57 - 6 is Closed, 126D57 - 7 is Closed, 126D57 - 8 is Closed, Back Door is Closed, Bedroom Window is Closed, Downstairs CO is Closed, Downstairs Heat is Not Reset, Downstairs Smoke is Not Reset, Front Door is Closed, Glass Break is Closed, Kitchen Door is Closed, Kitchen Window is Closed, LIV KIT Window is Closed, Master Window is Closed, Office Window is Closed, Panel Camera is Idle, System is Closed, Upstairs CO is Closed, Upstairs Heat is Not Reset, Upstairs Smoke is Not Reset, Upstairs Window 1 is Closed, Upstairs Window 2 is Closed

**Comment by uvjustin** [comment]
The component doesn't currently support/detect STATE_ALARM_TRIGGERED. Unfortunately, I'm away from the alarm panel for the foreseeable future so I may have a hard time adding that functionality (I'd have to trigger the alarm while not being there). I'd welcome any PRs that would address this. One thing to keep in mind is that since the component works by polling, state changes are not instantaneous.
One workaround might be to detect changes in the sensor_status field itself - I'm assuming if it's triggered, the first value will not read "System OK". Maybe @aechelon @clsferguson or @MichaelThomasMPT can help?

**Comment by aechelon** [comment]
@mikesalz I'm not sure that the System OK flag will change during an alarm trigger event.  
I think that flag refers to the system's connectivity (both to your sensors and to the monitoring station).

However, since you already have sensor for windows and glass break, smoke, etc you could just use state changes of those as automation triggers, and follow the trigger with a condition to determine the alarm's arming state.  

If the alarm state is armed (armed_home or armed_away) when a sensor changes state, then your alarm is likely going off.  You may choose to ignore motion sensors if the alarm state is armed_home or introduce extra conditions to bypass specific sensors under different conditions.  Likewise, you could use non-alarm.com sensors along with the alarm's arming state to trigger automations (e.g. If the alarm state is armed_home and an outdoor motion sensor detects motion, then turn on the porch lights).

If you set up the automation triggers through HA's built-in automations then you'll need either one automation per sensor, or a single automation with multiple triggers (see [multiple triggers](https://www.home-assistant.io/docs/automation/trigger/)).  Alternatively you could implement this with a Node-RED flow.  These types of automations are really easy to model and debug in Node-RED.

Either way you go (HA automation or NR flow), I would recommend centralizing the resulting action(s) in the event of a trigger and positive alarm arming state condition check into a single script (resulting in a single service call in your HA automation action and/or a single NR node).

If you haven't used Node-RED with HA, [The Hook Up](https://www.youtube.com/channel/UC2gyzKcHbYfqoXA5xbyGXtQ) channel has a [great series on it](https://www.youtube.com/watch?v=SuoSXVqjyfc).

Good luck!

**Comment by mikesalz** [comment]
Thanks for the responses, @aechelon and @uvjustin!  I think I see where you are going with the suggestion of checking sensors if the alarm is armed.  But there is a problem with that: If someone opens the door and walks in the house to disarm the alarm, the door sensor would fire and then trigger my automation.  Maybe I need to just let the alarm sound and watch the status to see what changes.  I just have to make sure to remember my passcode when ADT calls to check on the house! :)

**Comment by aechelon** [comment]
@mikesalz Both HA automations and Node-RED flows allow you to introduce delays and additional conditions in the "action" portion of your automation/flow.  Once your sensor(s) are triggered and the automation has verified the alarm is armed you can introduce a delay and then check if the alarm state has changed to disarmed -- if not, proceed to trigger the rest of your automation, otherwise bail out.  You'll likely need your delay to be a little longer than the alarm delay on the panel (the amount of time provided to disable the alarm before it goes off) to compensate for the polling delay.

You may also want to introduce an extra variable to prevent multiple sensors from triggering the automation simultaneously (e.g. if someone opened a door and then set off a few motion sensors on their way to disarm panel).  The "action" portion of your script would toggle that variable to TRUE immediately and change it back to FALSE before returning.  Then the condition portion of your automation would check for FALSE (and therefore be prevented from proceeding to the "action" portion if the automation is already running from a different trigger.)
