### ISSUE TITLE
Activating takes long time / not working

### ISSUE THREAD

**Issue by Brkie** [uvjustin/alarmdotcomajax#12]
Hi,

Pretty new to this but doing my best. I use this integration for my alarm and I also Homekit integration. I got all the sensors working and showing correct (and fast) data. But when I try to arm my alarm, both in HA dashboard and in Homekit, it takes 'forever' (long time), sometimes it sucess but usually not. 

When I go in to my alarm.com app, and arm "night" mode, I directly get a 'push' from my homeapp that the alarm state is changed - no lag or so. 

Is there something I can to to speedup / sucess with arming the alarm thru HA? 

Thx

**Comment by uvjustin** [comment]
Our integration works via web scraping and is not supported by Alarm.com. We don't have an API to work with that we can get callbacks from, so we have to update the state by "polling" or refreshing it periodically.
Home Assistant internally refreshes the state every 30 seconds (the default SCAN_INTERVAL for alarm_control_panel entities). Additionally, this component refreshes the state directly after sending any arm/disarm command.
It's possible that the state that we get right after sending the command is not updated yet, so the state does not get updated until the next time Home Assistant requests an update. This should be within 30 seconds though, so I'm not sure why it is taking 'forever' in your case.
@aechelon Any thoughts? I can make a quick update that temporarily increases the update frequency after sending an arm/disarm command, but this doesn't seem to be the problem here...

**Comment by aechelon** [comment]
No need to update the default scan interval.  Home Assistant supports updating the scan interval using the scan_interval parameter through the configuration.yaml entry (alarmdotcomajax inherits the scan_interval parameter from the alarm_control_panel base component).  

Be advised that there have been reports of Alarm.com disabling accounts that poll too frequently.

Here's an example to lower the interval to 15 seconds:
```
# Alarm.com
 alarm_control_panel:
   platform: alarmdotcomajax
   username: !secret alarmdotcom_login
   password: !secret alarmdotcom_password
   scan_interval: 00:00:15
```

Also, as stated on [this thread ](https://community.home-assistant.io/t/alarm-com-list-index-out-of-range/170670/127?u=aechelon) the interval between status updates is largely dependent on the alarm system hardware.  

You could also try logging into your alarm.com account via the web browser interface and seeing if arming that way has the same lag.  This is effectively the same interface used by the plugin.  If so, then the issue is likely system-dependent.

**Comment by Brkie** [comment]
Hi again,

I dont think its the system. Connected thru 3G + WiFi, arms and dissarms in max 2 sec. 
I also use Apple Homeapp, homekit.

When I use my alarm.com app and arm > I directly get a notification from homekit & home assistant -> armed. Same when I un-arm. When I try to use Home assistant or homekit to arm or un-arm, it usually dont even arm, and when it arms - it takes up to 1 minut, but mostly it fails. 

So I dont think the scan interval is bad, my sensors (door & motion sensor) change status very fast, both in home app and home assistant.

**Comment by aechelon** [comment]
I have a similar setup (3G + WiFi) and updates after arming/disarming from HA take <2s.
Try logging into your alarm.com account via the web browser interface and seeing if arming that way has the same lag.

**Comment by Brkie** [comment]
You mean by logging in by standard browser at www.alarm.com? If yes - same result as before < 2 sec.

**Comment by aechelon** [comment]
Odd.  And you're running a recent/up-to-date HA instance?

**Comment by Brkie** [comment]
Yes, just updated to the last core update - same result. While testing, my summary is - arming / disarming by HA is taking very long time or not working at all. 

But when I arm thru the app or at the panel, it takes max 30 sec to inform HA that its armed. 

So the communication FROM HA to alarm.com seems to be the problem, but not opposite.

**Comment by uvjustin** [comment]
Strange...are you using the same login for the browser at www.alarm.com and in the configuration of the HA integration?

**Comment by Brkie** [comment]
Yes, same log in. I can upload a video if wanted?

**Comment by uvjustin** [comment]
Are there any zones that you are bypassing when arming? Are there any HA log warnings/errors when you arm/disarm?

**Comment by Brkie** [comment]
Ok I have found something. When I use ”arm home” it works. When I use ”arm night” it does not work. I have a swedish alarm from securiras thru alarm.com - I dont know if you all have those options? 

When I try to use homekit, still no sucess but I think that have to do something with HA & homekit integration.

Question is, why does nothing happen when I use ”night arm”?

Logs= no error, logs all my activity, it says even when I try to use night mode, but nothing happens...

**Comment by aechelon** [comment]
The Alarm.com web interface does not expose a "night arm" command, and so neither does the plugin.
The only options available through the web interface are "disarm", "arm-home", and "arm-away".

If you submitted any other command, then it would likely just be ignored.

**Comment by uvjustin** [comment]
@Brkie The reason it doesn't show up in the logs is a function of how HA deals with services/platforms and supported_features. Not all platforms under the same integration support the same features, so each platform specifies which subset of features it supports. In our case, our component declares it supports arm home and arm away (and all components under alarm_control_panel support disarm). When you call night arm, it goes through to the service handler since all the services are registered by the alarm_control_panel integration, but it ends up getting ignored here: https://github.com/home-assistant/core/blob/633f9b2f01131883cc8e70f4b1843d9630c88f34/homeassistant/helpers/service.py#L433 because our underlying platform does not support that feature. If you think this should result in a log message you could open an issue or PR at home-assistant/core to get this changed.
@aechelon Thanks as always!
