### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by gutch1** [uvjustin/alarmdotcomajax#16]
Thank you for this. It works but I had to disable two factor authentication. Can this be avoided?

**Comment by uvjustin** [comment]
This doesn't really make sense as the component would not be able to log in to your account if it had to verify a text message in order to complete log in.
In ADC you can create a separate login that you use only for HA, and you would only have to disable 2FA for that login. You would only need to give this login "Custom -> Remote Arming -> Full Control" permissions. You could use a very secure password for this login and rotate it as you see fit.

**Comment by gutch1** [comment]
Thanks for the suggestion and I'll look into that. I don't know how it wouldn't make sense though. For example, I can use two factor authentication to utilize alexa. Either way it works great.

**Comment by uvjustin** [comment]
I see what you mean.
Some services let you authorize once through OAuth, and instead of storing your username and password they store a token which gives them access to whatever features you authorize.
Unfortunately ADC does not support OAuth and actually does not really support any kind of third party interface. So we have to scrape their website (we emulate using the website).
Anyway, the separate login step I mentioned above would achieve the same thing that OAuth would. The separate login/password would function exactly like the token above. It would only have whatever access you authorized it to have, and you could revoke it at any time.

**Comment by slightlyskewed** [comment]
tried the dedicated HA user account in ADC, but it does not allow to provision the permissions you stated above. dont even see a way to enable web login for the alt account, am i missing something?

otherwise seems like a great secure work around

**Comment by uvjustin** [comment]
Try Users -> Manage Logins -> Add a Login

**Comment by uvjustin** [comment]
@slightlyskewed Any luck with that?

**Comment by slightlyskewed** [comment]
> @slightlyskewed Any luck with that?

sorry been out of town, worked perfectly. many thanks!
