### ISSUE TITLE
Multiple locations / accounts not working correctly

### ISSUE THREAD

**Issue by markus99** [uvjustin/alarmdotcomajax#5]
Environment:
```
- Running on Ubuntu 18.04.4 LTS on a NUC / Docker
- Supervisor 209
- HA version 106.2
```

I have Alarm.com setup for two locations, our home and our office (work).  The (now removed from HA) 'old' version used to allow this setup and treat them individually. 

**Configuration.yaml**:

```
alarm_control_panel:
  - platform: alarmdotcomajax
    name: work
    username: !secret alarmdotcom_user_work
    password: !secret alarmdotcom_pass_work
  - platform: alarmdotcomajax
    name: home
    username: !secret alarmdotcom_user_home
    password: !secret alarmdotcom_pass_home
```
If I view my ```alarm_control_panel``` entries, you'll notice it's duplicating / combining them - instead of treating them as two separate locations:
![image](https://user-images.githubusercontent.com/2835274/77469530-3acdfe80-6ddd-11ea-8a41-faab1ff3bc34.png)

Worth pointing out these logins are each unique to ONLY the location and don't have access to the other.

**Comment by uvjustin** [comment]
Thanks for the info. Since this component is essentially the same as the "old" version, it would seem that the problem would lie in the scraping in the pyalarmdotcom library. However, the fact that both configs give access to the same system points back to this alarmdotcom component.
When you say it's duplicating/combining them, do you mean that the zones are combined into one system? Or is it one system displaying the wrong info ie the info for the other one?

**Comment by markus99** [comment]
It appears to be the latter - both systems are showing the same information.  In this case above, both `alarm_control_panel.home` and `alarm_control_panel.work` are both showing the `home` system's information (arming status, sensor_status, etc.)

**Comment by uvjustin** [comment]
Are both entities able to arm that system?
One thought I had was maybe both the logins might have access to both systems underneath the hood (since the pyalarmdotcomajax code wasn't written to handle multiple systems and partitions - it just grabs the first system here https://github.com/uvjustin/pyalarmdotcomajax/blob/master/pyalarmdotcomajax/pyalarmdotcomajax.py:136), but if they're totally unrelated logins then I don't see how this is possible.
Unfortunately I don't have access to another login to help troubleshoot. Maybe @aechelon can help us?

**Comment by aechelon** [comment]
Hmmm...  I don't think that's it because in the forum thread @markus99 mentioned that using two different versions of the plugin with two different namespaces (webapi and ajax -- one for each account) works.  It's almost like it's ignoring the second set of credentials.

A quick test to verify that would be to switch the order of the definitions (i.e. define the home account first and the work account second).  If both instances report results for the home system after that change, then that would indicate that the second set of credentials are being ignored.

@markus99 can you run that test and report back?

I also only have one ADC system, but I was able to create a secondary login so I can debug which credentials are being provided to the pyalarmdotcomajax constructor.  I'll take a look.

I diff'd the original alarm_control_panel.py and the one in the custom_component and didn't see anything obvious there.  I'm now doing the same for Xorso's pyalarmdotcom and pyalarmdotcomajax.  

I'm not sure if this is something, but Xorso's implementation defined the class as:

`class Alarmdotcom:`

whereas pyalarmdotcomajax defines it as:

`class Alarmdotcom(object):`

The only reason that's suspicious to me is because the gc100 class in [this thread](https://community.home-assistant.io/t/request-for-help-with-multiple-configuration-entries-for-the-same-platform/128770/3) had the same issue and it's defined the same way,,,

Thoughts?

**Comment by markus99** [comment]
Updated configuration.yaml to:
```
  - platform: alarmdotcomajax
    name: work
    username: !secret alarmdotcom_user_work
    password: !secret alarmdotcom_pass_work
  - platform: alarmdotcomajax
    name: home
    username: !secret alarmdotcom_user_home
    password: !secret alarmdotcom_pass_home
```
This resulted in both `alarm_control_panel.home` and `alarm_control_panel.work` entities showing the `HOME` sensor_status.  

![image](https://user-images.githubusercontent.com/2835274/77559297-05331f00-6e8a-11ea-90ac-a37347371d8d.png)

Tested Developer Tools -> Services `alarm_control_panel.alarm_arm_home` on the `alarm_control_panel.home` and it armed the HOME alarm to stay, and then reflected this ARMED STAY status on BOTH `alarm_control_panel.home` and `alarm_control_panel.work` entities (as shown in image above)

Also tried the above on the `alarm_control_panel.work` and this armed the HOME alarm.  WORK alarm was left unchanged (check via alarm.com directly [using different login than in configuartion.yaml]).

Going to try reversing the order of the home/work in configuration.yaml and will report back.

**Comment by markus99** [comment]
Tried this for grins, same result as above
```
alarm_control_panel 1:
  - platform: alarmdotcomajax
    name: work
    username: !secret alarmdotcom_user_work
    password: !secret alarmdotcom_pass_work
    
alarm_control_panel 2:    
  - platform: alarmdotcomajax
    name: home
    username: !secret alarmdotcom_user_home
    password: !secret alarmdotcom_pass_home
```
Switching order now w/ a single `platform`

**Comment by markus99** [comment]
Flipped the order in configuration.yaml:
```
alarm_control_panel:
  - platform: alarmdotcomajax
    name: home
    username: !secret alarmdotcom_user_home
    password: !secret alarmdotcom_pass_home

  - platform: alarmdotcomajax
    name: work
    username: !secret alarmdotcom_user_work
    password: !secret alarmdotcom_pass_work
```
and resulted in flipping the sensors, now showing `WORK` for both `alarm_control_panel.home` and `alarm_control_panel.work` entities

![image](https://user-images.githubusercontent.com/2835274/77561809-32cd9780-6e8d-11ea-8bbe-72a2c9acb9e1.png)

UPDATE: Just rebooted a 2nd time after switching (`HOME` on top, `WORK` on bottom [as shown above]) and now it's showing the HOME statuses - so it might not matter what order these appear in within configuration.yaml - appears to be 'picking' one or the other...?
![image](https://user-images.githubusercontent.com/2835274/77562418-ff3f3d00-6e8d-11ea-988c-c776a5a8050f.png)

**Comment by uvjustin** [comment]
I think it might be because we are using the default aiohttp clientsession so we are sharing site cookies. You can test this by creating a new websession for each instance, changing line 91 of alarmdotcomajax/alarm_control_panel.py to:
self._websession = aiohttp.ClientSession()
and remember to import aiohttp at the top

**Comment by markus99** [comment]
Made those changes, restarted and the two separate locations **are** showing correctly.  Nice work on the fix, thank you @uvjustin !

**Comment by aechelon** [comment]
Good news!  I'd say that's a worthwhile change.

**Comment by aechelon** [comment]
Unrelated, I installed the plugin via HACS and it seems to be working fine.

**Comment by uvjustin** [comment]
@markus99 I pushed some changes that should use the existing websession for the first instance and create a new websession for additional instances. See if it works on your side?

**Comment by uvjustin** [comment]
@aechelon Did you add it to HACS?

**Comment by aechelon** [comment]
No, I didn't have to do anything special...  Apparently HACS is smart enough to notice that the file layout is conformant.  It even noticed that my local install of the integration is out-of-date just after you committed the latest change and offered me an option to update.  Very slick!

To install through HACS:

Add the integration repository as Category -> Integration using the SETTINGS page on the HACS interface,
Search for Alarm.com on the INTEGRATIONS page on the HACS interface, click on the Alarm.com card and click INSTALL.
If you had not installed the integration as a custom_component you will need to update your configuration.yaml as documented in the README

NOTE: If you previously installed the integration as a custom_component you will want to move or remove that directory before restarting HA.

**Comment by aechelon** [comment]
I posted instructions on the [HA thread](https://community.home-assistant.io/t/alarm-com-list-index-out-of-range/170670/116)

**Comment by aechelon** [comment]
Might also be worth adding these instructions to the installation section in the README.

**Comment by aechelon** [comment]
There also has to be some configuration element we're missing to provide HACS with a description of the module.

**Comment by markus99** [comment]
OK, just installed via HACS and rebooted.

Appears like this update **is working** correctly with multiple systems.  Showing unique / correct `sensor_status` for each location.

Thx @uvjustin !

**Comment by uvjustin** [comment]
@markus99 Great, will close this
@aechelon HACS developer instructions are here https://hacs.xyz/docs/publish/start . The description comes from the Github description - I'll throw one line in there now.
I don't use HACS so not sure how it works. How is it finding the repository?
